Fixed up CD pipeline to work from github releases instead of annotated tags

diff --git a/continuous-delivery/test_version_exists b/continuous-delivery/test_version_exists
--- a/continuous-delivery/test_version_exists
+++ b/continuous-delivery/test_version_exists
@@ -1,9 +1,18 @@
 #!/usr/bin/env bash
 set -e
-#force a failure if there's no tag
-git describe --abbrev=0
-#now get the tag
-CURRENT_TAG_VERSION=$(git describe --abbrev=0)
+set -x
+# force a failure if there's no tag
+git describe --tags
+# now get the tag
+CURRENT_TAG=$(git describe --tags | cut -f2 -dv)
+# convert v0.2.12-2-g50254a9 to 0.2.12
+CURRENT_TAG_VERSION=$(git describe --tags | cut -f1 -d'-' | cut -f2 -dv)
+# if there's a hash on the tag, then this is not a release tagged commit
+if [ "$CURRENT_TAG" != "$CURRENT_TAG_VERSION" ]; then
+    echo "Current tag version is not a release tag, cut a new release if you want to publish."
+    exit 1
+fi
+
 if pip install -vvv awsiotsdk==$CURRENT_TAG_VERSION; then
     echo "$CURRENT_TAG_VERSION is already in pypi, cut a new tag if you want to upload another version."
     exit 1
